# Generated by Django 5.1.15 on 2026-05-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('prefix', models.CharField(default='', max_length=20)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('pad_width', models.PositiveSmallIntegerField(default=6)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doc_type', 'year'), name='unique_doc_type_year')],
            },
        ),
    ]
