# Generated by Django 5.1.15 on 2026-05-23 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_writeattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('chat', 'Chat'), ('preview', 'Preview'), ('confirm', 'Confirm'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('tool_names', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='writeattempt',
            new_name='core_writea_user_id_cd0667_idx',
            old_name='core_writea_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='writeattempt',
            new_name='core_writea_ip_ce45c1_idx',
            old_name='core_writea_ip_created_idx',
        ),
        migrations.AddField(
            model_name='copilotauditevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='copilotauditevent',
            index=models.Index(fields=['user', 'created_at'], name='core_copilo_user_id_3ed798_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotauditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='core_copilo_event_t_553247_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotauditevent',
            index=models.Index(fields=['object_type', 'object_id'], name='core_copilo_object__87e769_idx'),
        ),
    ]
