# Generated by Django 5.1.15 on 2026-05-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_copilotauditevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="e.g. 'about', 'contact'. Set to 'home' or leave blank for the homepage.", unique=True)),
                ('html_content', models.TextField(blank=True, default='<h1>Welcome!</h1><p>Edit this page from your Website Editor inside the ERP.</p>')),
                ('is_homepage', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_homepage', 'title'],
            },
        ),
    ]
