# Generated by Django 5.1.15 on 2026-05-24 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publicpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('brand_name', models.CharField(default='My ERP Website', max_length=200)),
                ('primary_color', models.CharField(default='#0f172a', max_length=7)),
                ('secondary_color', models.CharField(default='#2563eb', max_length=7)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('custom_css', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
        migrations.AddField(
            model_name='publicpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Search engine summary. Keep under 160 characters.', max_length=160),
        ),
        migrations.AddField(
            model_name='publicpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255),
        ),
        migrations.AddField(
            model_name='publicpage',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='Open Graph sharing card image URL.', max_length=500),
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.publicpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
