# Generated by Django 5.1.15 on 2026-05-24 01:46

import webstore.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_websitesettings_publicpage_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='stripe_account_id',
            field=webstore.fields.EncryptedCharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='stripe_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='stripe_webhook_secret',
            field=webstore.fields.EncryptedCharField(blank=True, default='', max_length=1024),
        ),
    ]
