# Generated by Django 5.1.15 on 2026-05-25 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_websitesettings_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('purpose', models.TextField(blank=True)),
                ('prompt', models.TextField()),
                ('cadence_note', models.CharField(blank=True, help_text='Planning note only, for example: Weekday mornings. Routines run manually for now.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_agent_routine_name_per_owner')],
            },
        ),
    ]
