# Generated by Django 5.1.15 on 2026-05-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agentroutine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesettings',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='stripe_connected_at',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='stripe_publishable_key',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='stripe_webhook_secret',
        ),
    ]
