# Generated by Django 5.1.15 on 2026-05-23 01:26

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_payment_paymentapplication_historicalpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('stock', 'Stock item'), ('service', 'Service')], default='stock', max_length=20)),
                ('uom', models.CharField(default='ea', help_text='Unit of measure: ea, kg, hr, etc.', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('default_expense_account', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_postable': True, 'type': 'expense'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('default_revenue_account', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_postable': True, 'type': 'revenue'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('stock', 'Stock item'), ('service', 'Service')], default='stock', max_length=20)),
                ('uom', models.CharField(default='ea', help_text='Unit of measure: ea, kg, hr, etc.', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_expense_account', models.ForeignKey(blank=True, limit_choices_to={'is_postable': True, 'type': 'expense'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_expense_for_products', to='accounting.account')),
                ('default_revenue_account', models.ForeignKey(blank=True, limit_choices_to={'is_postable': True, 'type': 'revenue'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_revenue_for_products', to='accounting.account')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
    ]
