# Generated by Django 5.1.15 on 2026-05-23 02:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Alert when stock on hand is at or below this quantity.', max_digits=14),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Alert when stock on hand is at or below this quantity.', max_digits=14),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ref_doc_type', models.CharField(blank=True, max_length=50)),
                ('ref_doc_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, max_length=500)),
                ('lot_id', models.CharField(blank=True, max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
                'indexes': [models.Index(fields=['product', 'posted_at'], name='inventory_s_product_2986c3_idx'), models.Index(fields=['ref_doc_type', 'ref_doc_id'], name='inventory_s_ref_doc_fb99ff_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='stockmovement_qty_positive'), models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='stockmovement_unit_cost_nonneg')],
            },
        ),
        migrations.CreateModel(
            name='StockOnHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_on_hand', to='inventory.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='stockonhand_qty_nonneg')],
            },
        ),
    ]
