# Generated by Django 5.1.15 on 2026-05-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_historicalproduct_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='image',
            field=models.TextField(blank=True, help_text='Product thumbnail or icon.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product thumbnail or icon.', null=True, upload_to='products/'),
        ),
    ]
