# Generated by Django 5.1.15 on 2026-05-23 20:30

import django.core.validators
import django.db.models.deletion
import inventory.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_historicalproduct_image_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='image',
            field=models.TextField(blank=True, help_text='Product thumbnail or icon (JPG/PNG/GIF/WebP, max 5 MB).', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), inventory.models._validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product thumbnail or icon (JPG/PNG/GIF/WebP, max 5 MB).', null=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), inventory.models._validate_image_size]),
        ),
        migrations.CreateModel(
            name='HistoricalLot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product')),
            ],
            options={
                'verbose_name': 'historical lot',
                'verbose_name_plural': 'historical lots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.product')),
            ],
            options={
                'ordering': ['product', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSerialNumber',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('issued', 'Issued')], default='in_stock', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product')),
                ('lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.lot')),
            ],
            options={
                'verbose_name': 'historical serial number',
                'verbose_name_plural': 'historical serial numbers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('issued', 'Issued')], default='in_stock', max_length=20)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='inventory.lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.product')),
            ],
            options={
                'ordering': ['product', 'serial_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('product', 'lot_number'), name='unique_product_lot'),
        ),
        migrations.AddConstraint(
            model_name='serialnumber',
            constraint=models.UniqueConstraint(fields=('product', 'serial_number'), name='unique_product_serial'),
        ),
    ]
