# Generated by Django 5.1.15 on 2026-05-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_historicallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='is_manufacturable',
            field=models.BooleanField(default=True, help_text='Can be built on manufacturing orders.'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='is_purchasable',
            field=models.BooleanField(default=True, help_text='Can be selected on purchase orders and vendor bills.'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='is_sellable',
            field=models.BooleanField(default=True, help_text='Can be selected on sales orders and invoices.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_manufacturable',
            field=models.BooleanField(default=True, help_text='Can be built on manufacturing orders.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_purchasable',
            field=models.BooleanField(default=True, help_text='Can be selected on purchase orders and vendor bills.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sellable',
            field=models.BooleanField(default=True, help_text='Can be selected on sales orders and invoices.'),
        ),
    ]
