# Generated by Django 5.1.15 on 2026-05-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_historicalproduct_is_manufacturable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='is_quarantined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='is_quarantined',
            field=models.BooleanField(default=False),
        ),
    ]
