# Generated by Django 5.1.15 on 2026-05-24 01:30

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_historicalproduct_is_manufacturable_and_more'),
        ('sales', '0003_invoiceline_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(help_text='State / Province', max_length=120)),
                ('postal_code', models.CharField(max_length=24)),
                ('country', models.CharField(default='US', help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('phone', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='webstore/categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='webstore.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductStorefront',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('short_tagline', models.CharField(blank=True, help_text='One-liner shown under the title on cards and the PDP.', max_length=160)),
                ('online_description', models.TextField(blank=True, help_text='Marketing copy (HTML allowed). Separate from the internal product description.')),
                ('online_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price charged on the storefront. Leave 0 to fall back to Product.price.', max_digits=14)),
                ('compare_at_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Strike-through price for showing a discount (e.g. $40 crossed out). Set 0 to hide.', max_digits=14)),
                ('is_online_active', models.BooleanField(default=True, help_text='If unchecked, the product is hidden from the storefront catalog.')),
                ('is_featured', models.BooleanField(default=False, help_text="Highlighted in Featured Product blocks and 'featured' product grids.")),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webstore.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_sellable': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product')),
            ],
            options={
                'verbose_name': 'historical product storefront',
                'verbose_name_plural': 'historical product storefronts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductStorefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('short_tagline', models.CharField(blank=True, help_text='One-liner shown under the title on cards and the PDP.', max_length=160)),
                ('online_description', models.TextField(blank=True, help_text='Marketing copy (HTML allowed). Separate from the internal product description.')),
                ('online_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price charged on the storefront. Leave 0 to fall back to Product.price.', max_digits=14)),
                ('compare_at_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Strike-through price for showing a discount (e.g. $40 crossed out). Set 0 to hide.', max_digits=14)),
                ('is_online_active', models.BooleanField(default=True, help_text='If unchecked, the product is hidden from the storefront catalog.')),
                ('is_featured', models.BooleanField(default=False, help_text="Highlighted in Featured Product blocks and 'featured' product grids.")),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='webstore.category')),
                ('product', models.OneToOneField(limit_choices_to={'is_sellable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to='inventory.product')),
            ],
            options={
                'ordering': ['sort_order', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='webstore/products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webstore.productstorefront')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('cart_items', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_checkouts', to='webstore.address')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webstore_checkouts', to='sales.customer')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webstore_checkouts', to='sales.salesorder')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_checkouts', to='webstore.address')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='webstore_ch_status_a220d8_idx')],
            },
        ),
    ]
