# Generated by Django 5.1.15 on 2026-05-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_historicallocation_and_more'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanufacturingorder',
            name='production_location',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Warehouse location where assembly takes place.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='production_location',
            field=models.ForeignKey(blank=True, help_text='Warehouse location where assembly takes place.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_orders', to='inventory.location'),
        ),
    ]
