# Generated by Django 5.1.15 on 2026-05-23 02:22

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_historicalproduct_low_stock_threshold_and_more'),
        ('purchasing', '0002_historicalpurchaseorder_purchaseorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_received', 'Partially received'), ('received', 'Received'), ('billed', 'Billed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_received', 'Partially received'), ('received', 'Received'), ('billed', 'Billed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchasing.purchaseorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_received', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchasing.purchaseorderline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='inventory.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.goodsreceipt')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='inventory.stockmovement')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalGoodsReceipt',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseorder')),
            ],
            options={
                'verbose_name': 'historical goods receipt',
                'verbose_name_plural': 'historical goods receipts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['purchase_order', 'date'], name='purchasing__purchas_0a61a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_received__gt', 0)), name='goodsreceiptline_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='goodsreceiptline_cost_nonneg'),
        ),
    ]
