# Generated by Django 5.1.15 on 2026-05-23 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_goodsreceipt_is_reversed_goodsreceipt_reversed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, help_text='The Goods Receipt this bill was drafted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='purchasing.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The Goods Receipt this bill was drafted from.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.goodsreceipt'),
        ),
    ]
