# Generated by Django 5.1.15 on 2026-05-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_historicallocation_and_more'),
        ('purchasing', '0005_bill_goods_receipt_historicalbill_goods_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Warehouse where the stock is received.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='inventory.location'),
        ),
    ]
