# Generated by Django 5.1.15 on 2026-05-23 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalaccount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.journalentry'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status', 'date'], name='accounting__status_755796_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_doc_type', 'source_doc_id'], name='accounting__source__7bbaba_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'entry'], name='accounting__account_e026d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='journalline_debit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='journalline_credit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='journalline_exactly_one_side'),
        ),
    ]
