# Generated by Django 5.1.15 on 2026-05-23 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_payment_paymentapplication_historicalpayment'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_account',
            field=models.ForeignKey(limit_choices_to={'is_postable': True, 'type': 'asset'}, on_delete=django.db.models.deletion.PROTECT, related_name='payments_cash', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='paymentapplication',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounting.payment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['direction', 'date'], name='accounting__directi_1efef6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer'], name='accounting__custome_0f2c50_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentapplication',
            index=models.Index(fields=['doc_type', 'doc_id'], name='accounting__doc_typ_679680_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentapplication',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='paymentapp_amount_positive'),
        ),
    ]
