# Generated by Django 5.1.15 on 2026-05-23 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_historicalpayment_customer_and_more'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.vendor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchasing.vendor'),
        ),
    ]
