# Generated by Django 5.1.15 on 2026-05-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_historicallocation_and_more'),
        ('sales', '0002_historicalsalesorder_salesorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Warehouse from which the stock is issued.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.location'),
        ),
    ]
